# title of website
title: 导航

# description of website
description: mryyp's navigation site

# favicon of website
favicon: "./fix.png?size=40"

# your website url
url: https://mryyp.github.io/webnav/

# github profile url
github: "https://github.com/mryyp"

# footer message
footer: © 2023-2099 @mryyp

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 交流地址
      sites:
        - name: 掘金
          description: 开发者社区
          url: https://juejin.cn/
        - name: V2EX
          description: v2ex
          url: https://www.v2ex.com/
        - name: Discord
          description: Discord
          url: https://discord.com/servers
    - name: Mac软件
      sites:
        - name: wallhaven壁纸
          description: wallhaven壁纸
          url: https://wallhaven.cc/
        - name: appstorrent
          description: appstorrent
          url: https://appstorrent.ru/programs/
        - name: Macapp 分享频道
          description: Macapp 分享频道
          url: https://macapp.org.cn/
        - name: 马可波罗
          description: 马可波罗
          url: https://www.macbl.com/
        - name: 奇迹秀
          description: 奇迹秀
          url: https://www.qijishow.com/
    - name: 开发平台
      sites:
        - name: 微信公众平台
          description: 微信公众平台
          url: https://mp.weixin.qq.com/
        - name: 支付宝开放平台
          description: 支付宝开放平台
          url: https://open.alipay.com/
        - name: Uni-app
          description: Uni-app
          url: https://uniapp.dcloud.net.cn/
        - name: Github
          description: Github.com
          url: https://github.com/
        - name: 码云
          description: gitee.com
          url: https://gitee.com/
    - name: UI库
      sites:
        - name: Vant 4
          description: 轻量、可定制的移动端 Vue 组件库
          url: https://vant-contrib.gitee.io/vant/#/zh-CN/home
        - name: NutUI
          description: 京东风格的轻量级移动端组件库
          url: https://nutui.jd.com/#/
        - name: uView-plus 
          description: uview-plus，是全面兼容nvue的uni-app生态框架
          url: https://uiadmin.net/uview-plus/
        - name: TuniaoUI v2
          description: 图鸟UI，是基于uni-app进行开发的UI框架
          url: https://vue2.tuniaokj.com/
        - name: TuniaoUI v3
          description: TuniaoUI 组件库 Vue3 Typescript Uniapp版本
          url: https://vue3.tuniaokj.com/zh-CN/
        - name: ELementUI
          description: Element，一套为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库
          url: https://element.eleme.io/#/zh-CN
        - name: TMUI3.0
          description: 优质Vue3 TS Pinia Vite跨端组件库
          url: https://tmui.design/
    - name: 网页灵感
      sites:
        - name: Zero
          description: Zero
          url: https://zero.tech/
        - name: Species-in-pieces
          description: species
          url: http://www.species-in-pieces.com/#
        - name: tympanus
          description: tympanus
          url: https://tympanus.net/codrops/
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
        - name: CSS Design Awards
          description: Website Awards & Inspiration - CSS Gallery
          url: https://www.cssdesignawards.com/
        - name: The FWA
          description: FWA - showcasing innovation every day since 2000
          url: https://thefwa.com/
        - name: Reeoo
          description: web design inspiration and website gallery
          url: http://reeoo.com/
        - name: Designmunk
          description: Best Homepage Design Inspiration
          url: https://designmunk.com/
        - name: Best Websites Gallery
          description: Website Showcase Inspiration | Best Websites Gallery
          url: https://bestwebsite.gallery/
        - name: SiteSee
          description: SiteSee is a curated gallery of beautiful, modern websites collections.
          url: https://sitesee.co/
        - name: Site Inspire
          description: A CSS gallery and showcase of the best web design inspiration.
          url: https://www.siteinspire.com/
    - name: Chat-gpt 
      sites:
        - name: Gpt-1
          description: Gpt - 1
          url: https://c.binjie.fun/#/chat/1693147530585
        - name: MinisTer Ai
          description: 一键点击云模型，立即创造出惊艳的AI艺术作品！
          url: https://mst.ai/home
    - name: Vpn
      sites:
        - name: 魔戒
          description: 国内地址 mojie.ac 按量订阅
          url: https://mojie.cyou/#/dashboard
        - name: eevpn
          description: 按月订阅
          url: https://www.eevpn.com/#/login
        - name: sockboom
          description: 按量订阅-按月订阅
          url: https://sockboom.link/user
    - name: idea
      sites:
        - name: idea激活码-注册码
          description: intellij idea注册码,idea激活码,idea破解,idea破解插件,idea注册码在线生成
          url: http://idea.javatiku.cn/
        - name: idea-jetbrains
          description: idea 编辑器
          url: https://www.jetbrains.com/
        - name: VsCode
          description: VsCode
          url: https://code.visualstudio.com/
    - name: 影视网站
      sites:
        - name: 腾讯视频
          description: 腾讯视频
          url: https://v.qq.com/
        - name: 爱奇艺
          description: 爱奇艺
          url: https://www.iqiyi.com/
        - name: 海兔影院
          description: 海兔影院
          url: https://www.haitu.tv/
        - name: 爱欧乐影院
          description: 爱欧乐影院
          url: https://www.iole.tv/
    - name: 常用推荐
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: PDF转换
          description: PDF转WORD 以及更多免费的在线格式转换工具
          url: https://www.alltoall.net/
        - name: 消除背景
          description: 上传一张图片以消除背景
          url: https://www.remove.bg/zh/upload
        - name: Api
          description: 免费Api
          url: http://txapi.cn/api
        - name: 量化文档
          description: 量化文档
          url: https://akshare.akfamily.xyz/platform.html#id1
        - name: musclewiki
          description: 健身网站
          url: https://musclewiki.com/
        - name: 草料二维码
          description: 草料二维码
          url: https://cli.im/
        - name: 加文字水印
          description: 加文字水印
          url: https://uutool.cn/img-watermark/
        - name: 文档格式转换
          description: 文档格式转换
          url: https://convert.io/cn/archive-converter
    - name: 在线配色
      sites:
        - name: 中国色
          description: http://zhongguose.com/
          url: http://zhongguose.com/
        - name: 日本色
          description: https://nipponcolors.com/
          url: https://nipponcolors.com/
        - name: webgradients
          description: WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part of your website.
          url: https://webgradients.com/
        - name: trianglify
          description: Trianglify Generator
          url: http://qrohlf.com/trianglify-generator/
    - name: 图标素材
      sites:
        - name: undraw矢量插画
          description: undraw矢量插画
          url: https://undraw.co/illustrations
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
    - name: 字体资源
      sites:
        - name: 字体天下
          description: 字体天下
          url: https://www.fonts.net.cn/
        - name: Google Font
          description: Making the web more beautiful, fast, and open through great typography
          url: https://fonts.google.com/
        - name: Abstract Fonts
          description: Abstract Fonts (13,866 free fonts)
          url: http://www.abstractfonts.com/
    - name: PPT资源
      sites:
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: 中文业界资讯站
          description: 中文业界资讯站
          url: https://www.cnbeta.com.tw/

